# Generated by Django 4.2.23 on 2025-07-10 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Firm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firm_name', models.CharField(help_text='The official name of the firm.', max_length=255, unique=True)),
                ('tagline', models.CharField(blank=True, help_text='A short, memorable slogan or mission statement.', max_length=500, null=True)),
                ('founded_year', models.PositiveIntegerField(blank=True, help_text='The year the firm was established.', null=True)),
                ('email', models.EmailField(blank=True, help_text='Primary contact email for the firm.', max_length=254, null=True)),
                ('website', models.URLField(blank=True, help_text='Official website URL.', null=True)),
                ('phone', models.CharField(blank=True, help_text='Primary contact phone number.', max_length=50, null=True)),
                ('address', models.CharField(blank=True, help_text='Principal office address, e.g., Wilmington, Delaware, USA', max_length=255, null=True)),
                ('vision', models.TextField(blank=True, help_text="The firm's long-term vision statement.", null=True)),
                ('mission', models.TextField(blank=True, help_text="The firm's core mission and purpose.", null=True)),
                ('approach_summary', models.TextField(blank=True, help_text="A summary of the firm's unique approach and methodology.", null=True)),
                ('services_offered', models.JSONField(blank=True, help_text="List of key services, e.g., ['Planning', 'Monitoring', 'Evaluation']", null=True)),
                ('core_expertise', models.JSONField(blank=True, help_text="List of cross-cutting expertise, e.g., ['MEL', 'Gender and Social Inclusion']", null=True)),
                ('methodologies', models.JSONField(blank=True, help_text="List of specific evaluation methodologies used, e.g., ['Contribution Analysis', 'Process Tracing']", null=True)),
                ('key_statistics', models.JSONField(blank=True, help_text="Key impact numbers, e.g., {'donor_funding': '140M', 'countries': 40}", null=True)),
                ('thematic_sectors', models.JSONField(blank=True, help_text="List of sectors the firm works in, e.g., ['Education', 'Health', 'Human Rights']", null=True)),
                ('donor_experience', models.JSONField(blank=True, help_text='List of funders the firm has worked with.', null=True)),
                ('geographical_reach', models.JSONField(blank=True, help_text='List of regions or continents of operation.', null=True)),
                ('quality_assurance_statement', models.TextField(blank=True, help_text='Standard text describing QA mechanisms.', null=True)),
                ('ethical_commitment_statement', models.TextField(blank=True, help_text='Standard text on ethical and child-friendly research.', null=True)),
                ('sustainability_statement', models.TextField(blank=True, help_text='Standard text on building for sustainability and adaptability.', null=True)),
            ],
        ),
    ]
