# Generated by Django 4.2.23 on 2025-07-10 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consultant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('linkedin', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Firm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firm_name', models.CharField(help_text='The official name of the firm.', max_length=255, unique=True)),
                ('tagline', models.CharField(blank=True, help_text='A short, memorable slogan or mission statement.', max_length=500, null=True)),
                ('founded_year', models.PositiveIntegerField(blank=True, help_text='The year the firm was established.', null=True)),
                ('email', models.EmailField(blank=True, help_text='Primary contact email for the firm.', max_length=254, null=True)),
                ('website', models.URLField(blank=True, help_text='Official website URL.', null=True)),
                ('phone', models.CharField(blank=True, help_text='Primary contact phone number.', max_length=50, null=True)),
                ('address', models.CharField(blank=True, help_text='Principal office address, e.g., Wilmington, Delaware, USA', max_length=255, null=True)),
                ('vision', models.TextField(blank=True, help_text="The firm's long-term vision statement.", null=True)),
                ('mission', models.TextField(blank=True, help_text="The firm's core mission and purpose.", null=True)),
                ('approach_summary', models.TextField(blank=True, help_text="A summary of the firm's unique approach and methodology.", null=True)),
                ('services_offered', models.JSONField(blank=True, help_text="List of key services, e.g., ['Planning', 'Monitoring', 'Evaluation']", null=True)),
                ('core_expertise', models.JSONField(blank=True, help_text="List of cross-cutting expertise, e.g., ['MEL', 'Gender and Social Inclusion']", null=True)),
                ('methodologies', models.JSONField(blank=True, help_text="List of specific evaluation methodologies used, e.g., ['Contribution Analysis', 'Process Tracing']", null=True)),
                ('key_statistics', models.JSONField(blank=True, help_text="Key impact numbers, e.g., {'donor_funding': '140M', 'countries': 40}", null=True)),
                ('thematic_sectors', models.JSONField(blank=True, help_text="List of sectors the firm works in, e.g., ['Education', 'Health', 'Human Rights']", null=True)),
                ('donor_experience', models.JSONField(blank=True, help_text='List of funders the firm has worked with.', null=True)),
                ('geographical_reach', models.JSONField(blank=True, help_text='List of regions or continents of operation.', null=True)),
                ('quality_assurance_statement', models.TextField(blank=True, help_text='Standard text describing QA mechanisms.', null=True)),
                ('ethical_commitment_statement', models.TextField(blank=True, help_text='Standard text on ethical and child-friendly research.', null=True)),
                ('sustainability_statement', models.TextField(blank=True, help_text='Standard text on building for sustainability and adaptability.', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('authors', models.CharField(max_length=500)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('publisher', models.CharField(blank=True, max_length=255, null=True)),
                ('link', models.URLField(blank=True, null=True)),
                ('consultant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publications', to='profiles.consultant')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('client', models.CharField(blank=True, max_length=255, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('project_summary', models.TextField(blank=True, null=True)),
                ('sectors', models.JSONField(blank=True, null=True)),
                ('methodologies', models.JSONField(blank=True, null=True)),
                ('firm_portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='profiles.firm')),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=100)),
                ('level', models.CharField(max_length=100)),
                ('consultant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='languages', to='profiles.consultant')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(max_length=255)),
                ('institution', models.CharField(max_length=255)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('start_year', models.DateField(blank=True, null=True)),
                ('end_year', models.DateField(blank=True, null=True)),
                ('field_of_study', models.CharField(blank=True, max_length=255, null=True)),
                ('graduation_status', models.CharField(blank=True, max_length=100, null=True)),
                ('dissertation_title', models.CharField(blank=True, max_length=500, null=True)),
                ('dissertation_link', models.URLField(blank=True, max_length=2000, null=True)),
                ('consultant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education', to='profiles.consultant')),
            ],
        ),
        migrations.AddField(
            model_name='consultant',
            name='firms',
            field=models.ManyToManyField(blank=True, help_text='Firms this consultant is associated with.', to='profiles.firm'),
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certification_name', models.CharField(max_length=255)),
                ('issuer', models.CharField(max_length=255)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('certification_link', models.URLField(blank=True, null=True)),
                ('consultant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='profiles.consultant')),
            ],
        ),
        migrations.CreateModel(
            name='ConsultantRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_title', models.CharField(help_text='e.g., Lead Evaluator, Data Analyst, Project Manager', max_length=255)),
                ('role_description', models.TextField(blank=True, null=True)),
                ('tasks', models.TextField(blank=True, help_text='Bulleted or paragraph list of specific tasks performed.', null=True)),
                ('consultant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='profiles.consultant')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='profiles.project')),
            ],
            options={
                'unique_together': {('project', 'consultant')},
            },
        ),
    ]
