# Generated by Django 4.2.23 on 2025-07-10 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certification',
            name='certification_link',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='consultant',
            name='linkedin',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='firm',
            name='website',
            field=models.URLField(blank=True, help_text='Official website URL.', max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='link',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
    ]
