# Generated by Django 4.2.23 on 2025-07-10 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_consultant_publication_language_education_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='date_range',
        ),
        migrations.AddField(
            model_name='assignment',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='dissertation_link',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
    ]
