# Generated by Django 4.2.23 on 2025-07-11 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_consultant_firms_alter_project_firm_portfolio'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultant',
            name='summary_profile',
            field=models.TextField(blank=True, null=True),
        ),
    ]
